using System.Collections.ObjectModel;

namespace UnicodeGenerator
{
    public static class UnicodeBlock
    {
        private static readonly IList<UnicodeBlockData> collection = new List<UnicodeBlockData>()
        {
            new UnicodeBlockData("0 BMP", "U+0000～U+007F", "基本拉丁字母"),
            new UnicodeBlockData("0 BMP", "U+0080～U+00FF", "拉丁字母補充－1"),
            new UnicodeBlockData("0 BMP", "U+0100～U+017F", "拉丁字母擴展－A"),
            new UnicodeBlockData("0 BMP", "U+0180～U+024F", "拉丁字母擴展－B"),
            new UnicodeBlockData("0 BMP", "U+0250～U+02AF", "國際音標擴展"),
            new UnicodeBlockData("0 BMP", "U+02B0～U+02FF", "佔位修飾符號"),
            new UnicodeBlockData("0 BMP", "U+0300～U+036F", "組合附加符號"),
            new UnicodeBlockData("0 BMP", "U+0370～U+03FF", "希臘字母和科普特字母"),
            new UnicodeBlockData("0 BMP", "U+0400～U+04FF", "西里爾字母"),
            new UnicodeBlockData("0 BMP", "U+0500～U+052F", "西里爾字母補充"),
            new UnicodeBlockData("0 BMP", "U+0530～U+058F", "亞美尼亞字母"),
            new UnicodeBlockData("0 BMP", "U+0590～U+05FF", "希伯來文字母"),
            new UnicodeBlockData("0 BMP", "U+0600～U+06FF", "阿拉伯文字母"),
            new UnicodeBlockData("0 BMP", "U+0700～U+074F", "敘利亞字母"),
            new UnicodeBlockData("0 BMP", "U+0750～U+077F", "阿拉伯文補充"),
            new UnicodeBlockData("0 BMP", "U+0780～U+07BF", "它拿字母"),
            new UnicodeBlockData("0 BMP", "U+07C0～U+07FF", "西非書面文字"),
            new UnicodeBlockData("0 BMP", "U+0800～U+083F", "撒瑪利亞字母"),
            new UnicodeBlockData("0 BMP", "U+0840～U+085F", "曼達安字母（Mandaic）"),
            new UnicodeBlockData("0 BMP", "U+0860～U+086F", "敘利亞文補充"),
            new UnicodeBlockData("0 BMP", "U+0870～U+089F", "阿拉伯字母擴展－B"),
            new UnicodeBlockData("0 BMP", "U+08A0～U+08FF", "阿拉伯字母擴展－A"),
            new UnicodeBlockData("0 BMP", "U+0900～U+097F", "天城文"),
            new UnicodeBlockData("0 BMP", "U+0980～U+09FF", "孟加拉文"),
            new UnicodeBlockData("0 BMP", "U+0A00～U+0A7F", "古木基文"),
            new UnicodeBlockData("0 BMP", "U+0A80～U+0AFF", "古吉拉特文"),
            new UnicodeBlockData("0 BMP", "U+0B00～U+0B7F", "奧里亞文"),
            new UnicodeBlockData("0 BMP", "U+0B80～U+0BFF", "泰米爾文"),
            new UnicodeBlockData("0 BMP", "U+0C00～U+0C7F", "泰盧固文"),
            new UnicodeBlockData("0 BMP", "U+0C80～U+0CFF", "卡納達文"),
            new UnicodeBlockData("0 BMP", "U+0D00～U+0D7F", "馬拉雅拉姆文"),
            new UnicodeBlockData("0 BMP", "U+0D80～U+0DFF", "僧伽羅文"),
            new UnicodeBlockData("0 BMP", "U+0E00～U+0E7F", "泰文"),
            new UnicodeBlockData("0 BMP", "U+0E80～U+0EFF", "寮文"),
            new UnicodeBlockData("0 BMP", "U+0F00～U+0FFF", "藏文"),
            new UnicodeBlockData("0 BMP", "U+1000～U+109F", "緬甸文"),
            new UnicodeBlockData("0 BMP", "U+10A0～U+10FF", "喬治亞字母"),
            new UnicodeBlockData("0 BMP", "U+1100～U+11FF", "諺文字母"),
            new UnicodeBlockData("0 BMP", "U+1200～U+137F", "衣索比亞字母"),
            new UnicodeBlockData("0 BMP", "U+1380～U+139F", "衣索比亞字母補充"),
            new UnicodeBlockData("0 BMP", "U+13A0～U+13FF", "切羅基文"),
            new UnicodeBlockData("0 BMP", "U+1400～U+167F", "統一加拿大原住民音節文字"),
            new UnicodeBlockData("0 BMP", "U+1680～U+169F", "歐甘字母"),
            new UnicodeBlockData("0 BMP", "U+16A0～U+16FF", "盧恩字母"),
            new UnicodeBlockData("0 BMP", "U+1700～U+171F", "他加祿字母"),
            new UnicodeBlockData("0 BMP", "U+1720～U+173F", "哈努諾文（Hanunoo）"),
            new UnicodeBlockData("0 BMP", "U+1740～U+175F", "布希德字母"),
            new UnicodeBlockData("0 BMP", "U+1760～U+177F", "塔格班瓦字母"),
            new UnicodeBlockData("0 BMP", "U+1780～U+17FF", "高棉文"),
            new UnicodeBlockData("0 BMP", "U+1800～U+18AF", "蒙古文"),
            new UnicodeBlockData("0 BMP", "U+18B0～U+18FF", "統一加拿大原住民音節文字擴充"),
            new UnicodeBlockData("0 BMP", "U+1900～U+194F", "林布文"),
            new UnicodeBlockData("0 BMP", "U+1950～U+197F", "德宏傣文（Tai Le）"),
            new UnicodeBlockData("0 BMP", "U+1980～U+19DF", "新傣仂文"),
            new UnicodeBlockData("0 BMP", "U+19E0～U+19FF", "高棉文符號"),
            new UnicodeBlockData("0 BMP", "U+1A00～U+1A1F", "布吉文"),
            new UnicodeBlockData("0 BMP", "U+1A20～U+1AAF", "老傣文"),
            new UnicodeBlockData("0 BMP", "U+1AB0～U+1AFF", "組合附加符號擴展"),
            new UnicodeBlockData("0 BMP", "U+1B00～U+1B7F", "峇里字母"),
            new UnicodeBlockData("0 BMP", "U+1B80～U+1BBF", "巽他字母"),
            new UnicodeBlockData("0 BMP", "U+1BC0～U+1BFF", "巴塔克字母（Batak）"),
            new UnicodeBlockData("0 BMP", "U+1C00～U+1C4F", "絨巴文"),
            new UnicodeBlockData("0 BMP", "U+1C50～U+1C7F", "桑塔利文"),
            new UnicodeBlockData("0 BMP", "U+1C80～U+1C8F", "西里爾字母擴展－C"),
            new UnicodeBlockData("0 BMP", "U+1C90～U+1CBF", "喬治亞字母擴展"),
            new UnicodeBlockData("0 BMP", "U+1CC0～U+1CCF", "巽他字母補充"),
            new UnicodeBlockData("0 BMP", "U+1CD0～U+1CFF", "吠陀擴展"),
            new UnicodeBlockData("0 BMP", "U+1D00～U+1D7F", "音標擴展"),
            new UnicodeBlockData("0 BMP", "U+1D80～U+1DBF", "音標擴展補充"),
            new UnicodeBlockData("0 BMP", "U+1DC0～U+1DFF", "組合附加符號補充"),
            new UnicodeBlockData("0 BMP", "U+1E00～U+1EFF", "拉丁字母擴展附加"),
            new UnicodeBlockData("0 BMP", "U+1F00～U+1FFF", "希臘字母擴展"),
            new UnicodeBlockData("0 BMP", "U+2000～U+206F", "一般標點"),
            new UnicodeBlockData("0 BMP", "U+2070～U+209F", "上標及下標"),
            new UnicodeBlockData("0 BMP", "U+20A0～U+20CF", "貨幣符號"),
            new UnicodeBlockData("0 BMP", "U+20D0～U+20FF", "符號用組合附加符號"),
            new UnicodeBlockData("0 BMP", "U+2100～U+214F", "類字母符號"),
            new UnicodeBlockData("0 BMP", "U+2150～U+218F", "數字形式"),
            new UnicodeBlockData("0 BMP", "U+2190～U+21FF", "箭頭"),
            new UnicodeBlockData("0 BMP", "U+2200～U+22FF", "數學運算子"),
            new UnicodeBlockData("0 BMP", "U+2300～U+23FF", "雜項技術符號"),
            new UnicodeBlockData("0 BMP", "U+2400～U+243F", "控制圖形"),
            new UnicodeBlockData("0 BMP", "U+2440～U+245F", "光學字元識別"),
            new UnicodeBlockData("0 BMP", "U+2460～U+24FF", "圍繞字母數字"),
            new UnicodeBlockData("0 BMP", "U+2500～U+257F", "制表符"),
            new UnicodeBlockData("0 BMP", "U+2580～U+259F", "方塊元素"),
            new UnicodeBlockData("0 BMP", "U+25A0～U+25FF", "幾何圖形"),
            new UnicodeBlockData("0 BMP", "U+2600～U+26FF", "雜項符號"),
            new UnicodeBlockData("0 BMP", "U+2700～U+27BF", "裝飾符號"),
            new UnicodeBlockData("0 BMP", "U+27C0～U+27EF", "雜項數學符號－A"),
            new UnicodeBlockData("0 BMP", "U+27F0～U+27FF", "追加箭頭－A"),
            new UnicodeBlockData("0 BMP", "U+2800～U+28FF", "點字圖案"),
            new UnicodeBlockData("0 BMP", "U+2900～U+297F", "追加箭頭－B"),
            new UnicodeBlockData("0 BMP", "U+2980～U+29FF", "雜項數學符號－B"),
            new UnicodeBlockData("0 BMP", "U+2A00～U+2AFF", "補充數學運算子"),
            new UnicodeBlockData("0 BMP", "U+2B00～U+2BFF", "雜項符號和箭頭"),
            new UnicodeBlockData("0 BMP", "U+2C00～U+2C5F", "格拉哥里字母"),
            new UnicodeBlockData("0 BMP", "U+2C60～U+2C7F", "拉丁字母擴展－C"),
            new UnicodeBlockData("0 BMP", "U+2C80～U+2CFF", "科普特字母"),
            new UnicodeBlockData("0 BMP", "U+2D00～U+2D2F", "喬治亞字母補充"),
            new UnicodeBlockData("0 BMP", "U+2D30～U+2D7F", "提非納文"),
            new UnicodeBlockData("0 BMP", "U+2D80～U+2DDF", "衣索比亞字母擴充"),
            new UnicodeBlockData("0 BMP", "U+2DE0～U+2DFF", "西里爾字母擴展－A"),
            new UnicodeBlockData("0 BMP", "U+2E00～U+2E7F", "補充標點"),
            new UnicodeBlockData("0 BMP", "U+2E80～U+2EFF", "中日韓漢字部首補充"),
            new UnicodeBlockData("0 BMP", "U+2F00～U+2FDF", "康熙部首"),
            new UnicodeBlockData("0 BMP", "U+2FF0～U+2FFF", "表意文字描述字元"),
            new UnicodeBlockData("0 BMP", "U+3000～U+303F", "中日韓符號和標點"),
            new UnicodeBlockData("0 BMP", "U+3040～U+309F", "平假名"),
            new UnicodeBlockData("0 BMP", "U+30A0～U+30FF", "片假名"),
            new UnicodeBlockData("0 BMP", "U+3100～U+312F", "注音符號"),
            new UnicodeBlockData("0 BMP", "U+3130～U+318F", "諺文相容字母"),
            new UnicodeBlockData("0 BMP", "U+3190～U+319F", "漢文訓讀符號"),
            new UnicodeBlockData("0 BMP", "U+31A0～U+31BF", "注音符號擴展"),
            new UnicodeBlockData("0 BMP", "U+31C0～U+31EF", "中日韓筆畫"),
            new UnicodeBlockData("0 BMP", "U+31F0～U+31FF", "片假名語音擴展"),
            new UnicodeBlockData("0 BMP", "U+3200～U+32FF", "中日韓圍繞字元及月份"),
            new UnicodeBlockData("0 BMP", "U+3300～U+33FF", "中日韓相容字元"),
            new UnicodeBlockData("0 BMP", "U+3400～U+4DBF", "中日韓統一表意文字擴充區 A"),
            new UnicodeBlockData("0 BMP", "U+4DC0～U+4DFF", "易經六十四卦符號"),
            new UnicodeBlockData("0 BMP", "U+4E00～U+9FFF", "中日韓統一表意文字（基本區）", true),
            new UnicodeBlockData("0 BMP", "U+A000～U+A48F", "彝文音節"),
            new UnicodeBlockData("0 BMP", "U+A490～U+A4CF", "彝文部首"),
            new UnicodeBlockData("0 BMP", "U+A4D0～U+A4FF", "傈僳文"),
            new UnicodeBlockData("0 BMP", "U+A500～U+A63F", "瓦伊文"),
            new UnicodeBlockData("0 BMP", "U+A640～U+A69F", "西里爾字母擴展－B"),
            new UnicodeBlockData("0 BMP", "U+A6A0～U+A6FF", "巴姆穆文字（Bamum）"),
            new UnicodeBlockData("0 BMP", "U+A700～U+A71F", "聲調修飾符號"),
            new UnicodeBlockData("0 BMP", "U+A720～U+A7FF", "拉丁字母擴展－D"),
            new UnicodeBlockData("0 BMP", "U+A800～U+A82F", "錫爾赫特文（Syloti Nagri）"),
            new UnicodeBlockData("0 BMP", "U+A830～U+A83F", "通用印度數字形式（Common Indic Number Forms）"),
            new UnicodeBlockData("0 BMP", "U+A840～U+A87F", "八思巴文"),
            new UnicodeBlockData("0 BMP", "U+A880～U+A8DF", "條拉什特拉文（Saurashtra）"),
            new UnicodeBlockData("0 BMP", "U+A8E0～U+A8FF", "天城文擴展"),
            new UnicodeBlockData("0 BMP", "U+A900～U+A92F", "克耶字母"),
            new UnicodeBlockData("0 BMP", "U+A930～U+A95F", "勒姜字母"),
            new UnicodeBlockData("0 BMP", "U+A960～U+A97F", "諺文字母擴展－A"),
            new UnicodeBlockData("0 BMP", "U+A980～U+A9DF", "爪哇字母"),
            new UnicodeBlockData("0 BMP", "U+A9E0～U+A9FF", "緬甸文擴展－B"),
            new UnicodeBlockData("0 BMP", "U+AA00～U+AA5F", "占文"),
            new UnicodeBlockData("0 BMP", "U+AA60～U+AA7F", "緬甸文擴展－A"),
            new UnicodeBlockData("0 BMP", "U+AA80～U+AADF", "傣越文"),
            new UnicodeBlockData("0 BMP", "U+AAE0～U+AAFF", "梅泰文擴充"),
            new UnicodeBlockData("0 BMP", "U+AB00～U+AB2F", "衣索比亞字母擴充－A"),
            new UnicodeBlockData("0 BMP", "U+AB30～U+AB6F", "拉丁字母擴展－E"),
            new UnicodeBlockData("0 BMP", "U+AB70～U+ABBF", "切羅基文補充"),
            new UnicodeBlockData("0 BMP", "U+ABC0～U+ABFF", "梅泰文"),
            new UnicodeBlockData("0 BMP", "U+AC00～U+D7AF", "諺文音節"),
            new UnicodeBlockData("0 BMP", "U+D7B0～U+D7FF", "諺文字母擴展－B"),
            new UnicodeBlockData("0 BMP", "U+D800～U+DB7F", "高半代用區"),
            new UnicodeBlockData("0 BMP", "U+DB80～U+DBFF", "高半私人代用區"),
            new UnicodeBlockData("0 BMP", "U+DC00～U+DFFF", "低半代用區"),
            new UnicodeBlockData("0 BMP", "U+E000～U+F8FF", "私用區"),
            new UnicodeBlockData("0 BMP", "U+F900～U+FAFF", "中日韓相容表意文字"),
            new UnicodeBlockData("0 BMP", "U+FB00～U+FB4F", "字母表達形式"),
            new UnicodeBlockData("0 BMP", "U+FB50～U+FDFF", "阿拉伯字母表達形式－A"),
            new UnicodeBlockData("0 BMP", "U+FE00～U+FE0F", "變體選擇符"),
            new UnicodeBlockData("0 BMP", "U+FE10～U+FE1F", "豎排形式"),
            new UnicodeBlockData("0 BMP", "U+FE20～U+FE2F", "組合用半符號"),
            new UnicodeBlockData("0 BMP", "U+FE30～U+FE4F", "中日韓相容形式"),
            new UnicodeBlockData("0 BMP", "U+FE50～U+FE6F", "小寫變體形式"),
            new UnicodeBlockData("0 BMP", "U+FE70～U+FEFF", "阿拉伯字母表達形式－B"),
            new UnicodeBlockData("0 BMP", "U+FF00～U+FFEF", "半形及全形字元"),
            new UnicodeBlockData("0 BMP", "U+FFF0～U+FFFF", "特殊"),
            new UnicodeBlockData("1 SMP", "U+10000～U+1007F", "線形文字 B 音節文字"),
            new UnicodeBlockData("1 SMP", "U+10080～U+100FF", "線形文字 B 表意文字"),
            new UnicodeBlockData("1 SMP", "U+10100～U+1013F", "愛琴海數字"),
            new UnicodeBlockData("1 SMP", "U+10140～U+1018F", "古希臘數字"),
            new UnicodeBlockData("1 SMP", "U+10190～U+101CF", "古代符號"),
            new UnicodeBlockData("1 SMP", "U+101D0～U+101FF", "斐斯托斯圓盤"),
            new UnicodeBlockData("1 SMP", "U+10280～U+1029F", "呂基亞字母"),
            new UnicodeBlockData("1 SMP", "U+102A0～U+102DF", "卡里亞字母"),
            new UnicodeBlockData("1 SMP", "U+102E0～U+102FF", "科普特閏餘數字"),
            new UnicodeBlockData("1 SMP", "U+10300～U+1032F", "古義大利字母"),
            new UnicodeBlockData("1 SMP", "U+10330～U+1034F", "哥特字母"),
            new UnicodeBlockData("1 SMP", "U+10350～U+1037F", "古彼爾姆文"),
            new UnicodeBlockData("1 SMP", "U+10380～U+1039F", "烏加里特字母"),
            new UnicodeBlockData("1 SMP", "U+103A0～U+103DF", "古波斯楔形文字"),
            new UnicodeBlockData("1 SMP", "U+10400～U+1044F", "德瑟雷特字母"),
            new UnicodeBlockData("1 SMP", "U+10450～U+1047F", "蕭伯納字母"),
            new UnicodeBlockData("1 SMP", "U+10480～U+104AF", "奧斯曼亞字母"),
            new UnicodeBlockData("1 SMP", "U+104B0～U+104FF", "歐塞奇字母"),
            new UnicodeBlockData("1 SMP", "U+10500～U+1052F", "愛爾巴桑字母"),
            new UnicodeBlockData("1 SMP", "U+10530～U+1056F", "高加條阿爾巴尼亞字母"),
            new UnicodeBlockData("1 SMP", "U+10570～U+105BF", "維斯庫奇文"),
            new UnicodeBlockData("1 SMP", "U+10600～U+1077F", "線形文字 A"),
            new UnicodeBlockData("1 SMP", "U+10780～U+107BF", "拉丁字母擴展－F"),
            new UnicodeBlockData("1 SMP", "U+10800～U+1083F", "賽普勒斯音節文字"),
            new UnicodeBlockData("1 SMP", "U+10840～U+1085F", "帝國亞拉姆文"),
            new UnicodeBlockData("1 SMP", "U+10860～U+1087F", "帕爾邁拉字母"),
            new UnicodeBlockData("1 SMP", "U+10880～U+108AF", "納巴泰字母"),
            new UnicodeBlockData("1 SMP", "U+108E0～U+108FF", "哈特拉文"),
            new UnicodeBlockData("1 SMP", "U+10900～U+1091F", "腓尼基字母"),
            new UnicodeBlockData("1 SMP", "U+10920～U+1093F", "呂底亞字母"),
            new UnicodeBlockData("1 SMP", "U+10980～U+1099F", "麥羅埃文聖書體"),
            new UnicodeBlockData("1 SMP", "U+109A0～U+109FF", "麥羅埃文草書體"),
            new UnicodeBlockData("1 SMP", "U+10A00～U+10A5F", "佉盧文"),
            new UnicodeBlockData("1 SMP", "U+10A60～U+10A7F", "古南阿拉伯字母"),
            new UnicodeBlockData("1 SMP", "U+10A80～U+10A9F", "古北阿拉伯字母"),
            new UnicodeBlockData("1 SMP", "U+10AC0～U+10AFF", "摩尼字母"),
            new UnicodeBlockData("1 SMP", "U+10B00～U+10B3F", "阿維斯陀字母"),
            new UnicodeBlockData("1 SMP", "U+10B40～U+10B5F", "碑刻帕提亞文"),
            new UnicodeBlockData("1 SMP", "U+10B60～U+10B7F", "碑刻巴列維文"),
            new UnicodeBlockData("1 SMP", "U+10B80～U+10BAF", "詩篇巴列維文"),
            new UnicodeBlockData("1 SMP", "U+10C00～U+10C4F", "古突厥文"),
            new UnicodeBlockData("1 SMP", "U+10C80～U+10CFF", "古匈牙利字母"),
            new UnicodeBlockData("1 SMP", "U+10D00～U+10D3F", "哈乃斐羅興亞文字"),
            new UnicodeBlockData("1 SMP", "U+10E60～U+10E7F", "盧米文數字"),
            new UnicodeBlockData("1 SMP", "U+10E80～U+10EBF", "雅茲迪文"),
            new UnicodeBlockData("1 SMP", "U+10EC0～U+10EFF", "阿拉伯字母擴展－C"),
            new UnicodeBlockData("1 SMP", "U+10F00～U+10F2F", "古粟特字母"),
            new UnicodeBlockData("1 SMP", "U+10F30～U+10F6F", "粟特字母"),
            new UnicodeBlockData("1 SMP", "U+10F70～U+10FAF", "回鶻字母"),
            new UnicodeBlockData("1 SMP", "U+10FB0～U+10FDF", "花剌子模字母"),
            new UnicodeBlockData("1 SMP", "U+10FE0～U+10FFF", "埃利邁文"),
            new UnicodeBlockData("1 SMP", "U+11000～U+1107F", "婆羅米文"),
            new UnicodeBlockData("1 SMP", "U+11080～U+110CF", "凱提文"),
            new UnicodeBlockData("1 SMP", "U+110D0～U+110FF", "條拉僧平文字"),
            new UnicodeBlockData("1 SMP", "U+11100～U+1114F", "查克馬文"),
            new UnicodeBlockData("1 SMP", "U+11150～U+1117F", "馬哈佳尼文"),
            new UnicodeBlockData("1 SMP", "U+11180～U+111DF", "夏拉達文"),
            new UnicodeBlockData("1 SMP", "U+111E0～U+111FF", "古僧伽羅文數字"),
            new UnicodeBlockData("1 SMP", "U+11200～U+1124F", "可吉文"),
            new UnicodeBlockData("1 SMP", "U+11280～U+112AF", "穆爾塔尼文"),
            new UnicodeBlockData("1 SMP", "U+112B0～U+112FF", "庫達瓦迪文"),
            new UnicodeBlockData("1 SMP", "U+11300～U+1137F", "古蘭塔文"),
            new UnicodeBlockData("1 SMP", "U+11400～U+1147F", "紐瓦字母"),
            new UnicodeBlockData("1 SMP", "U+11480～U+114DF", "底羅僕多文"),
            new UnicodeBlockData("1 SMP", "U+11580～U+115FF", "悉曇文字"),
            new UnicodeBlockData("1 SMP", "U+11600～U+1165F", "莫迪文"),
            new UnicodeBlockData("1 SMP", "U+11660～U+1167F", "蒙古文補充"),
            new UnicodeBlockData("1 SMP", "U+11680～U+116CF", "塔克里文"),
            new UnicodeBlockData("1 SMP", "U+11700～U+1174F", "阿洪姆文"),
            new UnicodeBlockData("1 SMP", "U+11800～U+1184F", "多格拉文"),
            new UnicodeBlockData("1 SMP", "U+118A0～U+118FF", "瓦蘭齊地文"),
            new UnicodeBlockData("1 SMP", "U+11900～U+1195F", "島嶼字母"),
            new UnicodeBlockData("1 SMP", "U+119A0～U+119FF", "南迪城文"),
            new UnicodeBlockData("1 SMP", "U+11A00～U+11A4F", "札那巴札爾方形字母"),
            new UnicodeBlockData("1 SMP", "U+11A50～U+11AAF", "條永布文字"),
            new UnicodeBlockData("1 SMP", "U+11AB0～U+11ABF", "加拿大原住民音節文字擴展－A"),
            new UnicodeBlockData("1 SMP", "U+11AC0～U+11AFF", "包欽豪文"),
            new UnicodeBlockData("1 SMP", "U+11B00～U+11B5F", "天城文擴展－A"),
            new UnicodeBlockData("1 SMP", "U+11C00～U+11C6F", "拜克舒基文"),
            new UnicodeBlockData("1 SMP", "U+11C70～U+11CBF", "瑪欽文"),
            new UnicodeBlockData("1 SMP", "U+11D00～U+11D5F", "馬薩拉姆貢德文字"),
            new UnicodeBlockData("1 SMP", "U+11D60～U+11DAF", "貢賈拉貢德文字"),
            new UnicodeBlockData("1 SMP", "U+11EE0～U+11EFF", "望加錫文"),
            new UnicodeBlockData("1 SMP", "U+11F00～U+11F5F", "卡維文"),
            new UnicodeBlockData("1 SMP", "U+11FB0～U+11FBF", "老傈僳文補充"),
            new UnicodeBlockData("1 SMP", "U+11FC0～U+11FFF", "泰米爾文補充"),
            new UnicodeBlockData("1 SMP", "U+12000～U+123FF", "楔形文字"),
            new UnicodeBlockData("1 SMP", "U+12400～U+1247F", "楔形文字數字和標點符號"),
            new UnicodeBlockData("1 SMP", "U+12480～U+1254F", "早期王朝楔形文字"),
            new UnicodeBlockData("1 SMP", "U+12F90～U+12FFF", "賽普勒斯－米諾斯文字"),
            new UnicodeBlockData("1 SMP", "U+13000～U+1342F", "埃及聖書體"),
            new UnicodeBlockData("1 SMP", "U+13430～U+1345F", "埃及聖書體格式控制"),
            new UnicodeBlockData("1 SMP", "U+14400～U+1467F", "安納托利亞象形文字"),
            new UnicodeBlockData("1 SMP", "U+16800～U+16A3F", "巴姆穆文字補充"),
            new UnicodeBlockData("1 SMP", "U+16A40～U+16A6F", "默祿文"),
            new UnicodeBlockData("1 SMP", "U+16A70～U+16ACF", "唐薩文"),
            new UnicodeBlockData("1 SMP", "U+16AD0～U+16AFF", "巴薩文"),
            new UnicodeBlockData("1 SMP", "U+16B00～U+16B8F", "救世苗文"),
            new UnicodeBlockData("1 SMP", "U+16E40～U+16E9F", "梅德法伊德林文"),
            new UnicodeBlockData("1 SMP", "U+16F00～U+16F9F", "柏格理苗文"),
            new UnicodeBlockData("1 SMP", "U+16FE0～U+16FFF", "表意符號和標點符號"),
            new UnicodeBlockData("1 SMP", "U+17000～U+187FF", "西夏文"),
            new UnicodeBlockData("1 SMP", "U+18800～U+18AFF", "西夏文部件"),
            new UnicodeBlockData("1 SMP", "U+18B00～U+18CFF", "契丹小字"),
            new UnicodeBlockData("1 SMP", "U+18D00～U+18D7F", "西夏文補充"),
            new UnicodeBlockData("1 SMP", "U+1AFF0～U+1AFFF", "假名擴展－B"),
            new UnicodeBlockData("1 SMP", "U+1B000～U+1B0FF", "假名補充"),
            new UnicodeBlockData("1 SMP", "U+1B100～U+1B12F", "假名擴展－A"),
            new UnicodeBlockData("1 SMP", "U+1B130～U+1B16F", "小型假名擴充"),
            new UnicodeBlockData("1 SMP", "U+1B170～U+1B2FF", "女書"),
            new UnicodeBlockData("1 SMP", "U+1BC00～U+1BC9F", "杜普雷速記"),
            new UnicodeBlockData("1 SMP", "U+1BCA0～U+1BCAF", "速記格式控制符"),
            new UnicodeBlockData("1 SMP", "U+1CF00～U+1CFCF", "贊玫尼聖歌音樂符號"),
            new UnicodeBlockData("1 SMP", "U+1D000～U+1D0FF", "拜占庭音樂符號"),
            new UnicodeBlockData("1 SMP", "U+1D100～U+1D1FF", "音樂符號"),
            new UnicodeBlockData("1 SMP", "U+1D200～U+1D24F", "古希臘音樂記號"),
            new UnicodeBlockData("1 SMP", "U+1D2C0～U+1D2DF", "卡克托維克數字"),
            new UnicodeBlockData("1 SMP", "U+1D2E0～U+1D2FF", "瑪雅數字"),
            new UnicodeBlockData("1 SMP", "U+1D300～U+1D35F", "太玄經符號"),
            new UnicodeBlockData("1 SMP", "U+1D360～U+1D37F", "算籌"),
            new UnicodeBlockData("1 SMP", "U+1D400～U+1D7FF", "字母和數字符號"),
            new UnicodeBlockData("1 SMP", "U+1D800～U+1DAAF", "薩頓書寫符號"),
            new UnicodeBlockData("1 SMP", "U+1DF00～U+1DFFF", "拉丁字母擴展－G"),
            new UnicodeBlockData("1 SMP", "U+1E000～U+1E02F", "格拉哥里字母補充"),
            new UnicodeBlockData("1 SMP", "U+1E030～U+1E08F", "西里爾字母擴展－D"),
            new UnicodeBlockData("1 SMP", "U+1E100～U+1E14F", "創世紀苗文"),
            new UnicodeBlockData("1 SMP", "U+1E290～U+1E2BF", "投投文"),
            new UnicodeBlockData("1 SMP", "U+1E2C0～U+1E2FF", "文喬字母"),
            new UnicodeBlockData("1 SMP", "U+1E4D0～U+1E4FF", "蒙達里字母"),
            new UnicodeBlockData("1 SMP", "U+1E7E0～U+1E7FF", "衣索比亞字母擴充－B"),
            new UnicodeBlockData("1 SMP", "U+1E800～U+1E8DF", "門德基卡庫文"),
            new UnicodeBlockData("1 SMP", "U+1E900～U+1E95F", "阿德拉姆字母"),
            new UnicodeBlockData("1 SMP", "U+1EC70～U+1ECBF", "印度西亞格數字"),
            new UnicodeBlockData("1 SMP", "U+1ED00～U+1ED4F", "奧斯曼西亞格數字"),
            new UnicodeBlockData("1 SMP", "U+1EE00～U+1EEFF", "阿拉伯字母數字符號"),
            new UnicodeBlockData("1 SMP", "U+1F000～U+1F02F", "麻將牌"),
            new UnicodeBlockData("1 SMP", "U+1F030～U+1F09F", "多米諾骨牌"),
            new UnicodeBlockData("1 SMP", "U+1F0A0～U+1F0FF", "撲克牌"),
            new UnicodeBlockData("1 SMP", "U+1F100～U+1F1FF", "圍繞字母數字補充"),
            new UnicodeBlockData("1 SMP", "U+1F200～U+1F2FF", "圍繞表意文字補充"),
            new UnicodeBlockData("1 SMP", "U+1F300～U+1F5FF", "雜項符號和象形文字"),
            new UnicodeBlockData("1 SMP", "U+1F600～U+1F64F", "表情符號"),
            new UnicodeBlockData("1 SMP", "U+1F650～U+1F67F", "裝飾符號"),
            new UnicodeBlockData("1 SMP", "U+1F680～U+1F6FF", "交通和地圖符號"),
            new UnicodeBlockData("1 SMP", "U+1F700～U+1F77F", "鍊金術符號"),
            new UnicodeBlockData("1 SMP", "U+1F780～U+1F7FF", "幾何圖形擴展"),
            new UnicodeBlockData("1 SMP", "U+1F800～U+1F8FF", "追加箭頭－C"),
            new UnicodeBlockData("1 SMP", "U+1F900～U+1F9FF", "補充符號和象形文字"),
            new UnicodeBlockData("1 SMP", "U+1FA00～U+1FA6F", "棋類符號"),
            new UnicodeBlockData("1 SMP", "U+1FA70～U+1FAFF", "符號和象形文字擴充－A"),
            new UnicodeBlockData("1 SMP", "U+1FB00～U+1FBFF", "遺留計算符號"),
            new UnicodeBlockData("2 SIP", "U+20000～U+2A6DF", "中日韓統一表意文字擴充區 B"),
            new UnicodeBlockData("2 SIP", "U+2A700～U+2B73F", "中日韓統一表意文字擴充區 C"),
            new UnicodeBlockData("2 SIP", "U+2B740～U+2B81F", "中日韓統一表意文字擴充區 D"),
            new UnicodeBlockData("2 SIP", "U+2B820～U+2CEAF", "中日韓統一表意文字擴充區 E"),
            new UnicodeBlockData("2 SIP", "U+2CEB0～U+2EBEF", "中日韓統一表意文字擴充區 F"),
            new UnicodeBlockData("2 SIP", "U+2EBF0～U+2EE5F", "中日韓統一表意文字擴充區 I"),
            new UnicodeBlockData("2 SIP", "U+2F800～U+2FA1F", "中日韓相容表意文字補充區"),
            new UnicodeBlockData("3 TIP", "U+30000～U+3134F", "中日韓統一表意文字擴充區 G"),
            new UnicodeBlockData("3 TIP", "U+31350～U+323AF", "中日韓統一表意文字擴充區 H"),
            new UnicodeBlockData("14 SSP", "U+E0000～U+E007F", "標籤"),
            new UnicodeBlockData("14 SSP", "U+E0100～U+E01EF", "變體選擇符補充"),
            new UnicodeBlockData("15 PUA－A", "U+F0000～U+FFFFF", "補充私人使用區－A"),
            new UnicodeBlockData("16 PUA－B", "U+100000～U+10FFFF", "補充私人使用區－B")
        };

        public static ReadOnlyCollection<UnicodeBlockData> unicodeBlockDataList
        {
            get
            {
                return collection.AsReadOnly();
            }
        }
    }
}